server {
  listen 80;
  listen [::]:80;
  server_name tools.chatcanvas.online;

  root /var/www/one-for-all;
  index index.html;

  location /.well-known/acme-challenge/ {
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options SAMEORIGIN;
  add_header Referrer-Policy strict-origin-when-cross-origin;
}
